[project]
name = "sistema-musical-grafos"
version = "0.1.0"
description = "Sistema musical baseado em teoria dos grafos com geração de MIDI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mido>=1.3.3",
    "numpy>=2.4.1",
    "python-rtmidi>=1.5.8"
]