[project]
name = "trabalhofinal"
version = "0.1.0"
description = "Trabalho final com anÃ¡lise de dados e grafos"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pandas>=2.2.0",
    "numpy>=1.26.0",
    "matplotlib>=3.8.0",
    "networkx>=3.3"
    "openpyxl>=3.1.2"
]
